### ISSUE TITLE
Update so that it can use the slim loader

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-cordova#16]
In production mode.

**Comment by m-mujica** [comment]
For the default target there is no update needed to get steal-cordova working. I just tried with myhub app and the following build script:

```javascript
var path = require("path");
var slim = require("steal-tools/lib/build/slim");

var stealCordova = require("steal-cordova")({
	buildDir: "./build/cordova",
	id: "com.myhub",
	name: "MyHub",
	platforms: ["ios"],
	index: path.join(__dirname, "index.html"),
  files: []
});

var buildPromise = slim({
  main: "myhub",
  config: path.join(__dirname, "package.json!npm")
}, {
  minify: false
});

buildPromise
  .then(stealCordova.build)
  .then(function() {
    stealCordova.ios.emulate();
  })
  .catch(function(err) {
    console.log("Uh-oh! something went wrong: ", err);
  });
```

apart from some style issue, the app works fine in the ios simulator

![screen shot 2017-08-02 at 17 20 31](https://user-images.githubusercontent.com/724877/28899307-897ec70a-77a7-11e7-8aa8-9ed3bb2e4309.png)

![screen shot 2017-08-02 at 17 21 31](https://user-images.githubusercontent.com/724877/28899315-96e805f0-77a7-11e7-95fa-0ce02844b124.png)

![screen shot 2017-08-02 at 17 21 31](https://user-images.githubusercontent.com/724877/28899300-80599de4-77a7-11e7-891f-5fd185ea781f.png)

**Comment by m-mujica** [comment]
There is an issue with multiple targets though, first, the buildResult is an object where each key is the target name and its value is the actual buildResult of said target.

The first change required would be to update the build script so the `web` buildResult is passed to `stealCordoba.build`, like this:

```javascript
buildPromise
  .then(function(result) {
    return stealCordova.build(result.web);
  })
  .then(function() {
    stealCordova.ios.emulate();
  })
  .catch(function(err) {
    console.log("Uh-oh! something went wrong: ", err);
  });
```

then, the app works just fine. The only issue I see is that `steal-cordova` is going to copy the whole `dist` folder which also includes the output of other targets.

@matthewp should we change steal-cordova somehow so it only copies `dist/web`

Also, since there is major change needed to get this working I guess we should document how to do it, maybe expand the current guide with the steps I followed?

**Comment by matthewp** [comment]
What about the HTML it copies over? Does it not have a script tag for steal.production.js

**Comment by m-mujica** [comment]
it copies the file as is, since the slim loader does not need the steal tag it just works. 

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="./dist/web/bundles/myhub/myhub.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">Hello World.</div>
    <script async src="./dist/bundles/web/myhub/puppies/puppies.js"></script>
    <script async src="./dist/bundles/web/myhub/myhub.js"></script>
    <script async src="./dist/bundles/web/myhub/weather/weather.js"></script>
  </body>
</html>
```

that's the `index.html` page of myhub with multiple targets.

**Comment by m-mujica** [comment]
https://github.com/stealjs/steal-cordova/blob/6672d8279761ee5fdb84e28abd966b9a5e8b65e6/lib/steal-cordova.js#L110-L115

**Comment by matthewp** [comment]
@m-mujica How did the index.html get like that, though? It's from editing it manual, per the guide, right?

Think about it in a donejs context. DoneJS creates a `production.html` file. This is the file that is copied, along with the build artifacts by steal-cordova. It's the one that is updated to include the `env` in that code you posted.

**Comment by m-mujica** [comment]
@matthewp yep, that's the index.html file that I had to write...

well, if donejs integrates with the slim loader it's `production.html` would have to load the main bundle instead of using the `steal.production.js` script and when you passed the options to steal-cordova you provide the path to that index.html

```javascript
var stealCordova = require("steal-cordova")({
	buildDir: "./build/cordova",
	id: "com.myhub",
	name: "MyHub",
	platforms: ["ios"],
	index: path.join(__dirname, "index.html"),    <=====
  files: []
});
```

what am I missing?

**Comment by matthewp** [comment]
@m-mujica can this be closed?
